INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(0, NULL, 'NEPOZNATO', NULL, 'nepoznato', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(1, NULL, 'Bosna i Hercegovina', NULL, 'bosna-i-hercegovina', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(2, NULL, 'Hrvatska', NULL, 'hrvatska', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(3, NULL, 'Srbija', NULL, 'srbija', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(4, NULL, 'Crna Gora', NULL, 'crna-gora', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(5, NULL, 'Makedonija', NULL, 'makedonija', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(6, NULL, 'Slovenija', NULL, 'slovenija', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(7, NULL, 'Italija', NULL, 'italija', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(8, NULL, 'Rumunija', NULL, 'rumunija', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(9, NULL, 'Bugarska', NULL, 'bugarska', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(10, NULL, 'Grčka', NULL, 'grcka', '', NULL, 'Country', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(101, 1, 'Maglić', 'Foča', 'maglic-foca', '', 2386, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(102, 1, 'Volujak', 'Foča', 'volujak-foca', '', 2336, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(103, 1, 'Velika Ljubušnja', 'Foča', 'velika-ljubusnja-foca', '', 2238, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(104, 1, 'Čvrsnica', 'Posušje', 'cvrsnica-posusje', '', 2226, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(105, 1, 'Vranica', 'Gornji Vakuf', 'vranica-gornji-vakuf', '', 2110, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(106, 1, 'Prenj', 'Mostar', 'prenj-mostar', '', 2103, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(107, 1, 'Treskavica', 'Trnovo', 'treskavica-trnovo', '', 2086, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(108, 1, 'Vran', 'Jablanica', 'vran-jablanica', '', 2074, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(109, 1, 'Bjelašnica', 'Trnovo', 'bjelasnica-trnovo', '', 2067, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(110, 1, 'Lelija', 'Kalinovik', 'lelija-kalinovik', '', 2032, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(111, 1, 'Zelengora', 'Foča', 'zelengora-foca', '', 2014, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(112, 1, 'Cincar', 'Glamoč', 'cincar-glamoc', '', 2006, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(113, 1, 'Velež', 'Mostar', 'velez-mostar', '', 1968, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(114, 1, 'Visočica', 'Konjic', 'visocica-konjic', '', 1967, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(115, 1, 'Klekovača', 'Drvar', 'klekovaca-drvar', '', 1962, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(116, 1, 'Raduša', 'Prozor', 'radusa-prozor', '', 1956, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(117, 1, 'Vlašić', 'Travnik', 'vlasic-travnik', '', 1933, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(118, 1, 'Crvanj', 'Nevesinje', 'crvanj-nevesinje', '', 1921, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(119, 1, 'Dinara', 'Livno', 'dinara-livno', '', 1913, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(120, 1, 'Jahorina', 'Pale', 'jahorina-pale', '', 1910, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(121, 1, 'Vitorog', 'Šipovo/Glamoč', 'vitorog-sipovo/glamoc', '', 1907, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(122, 1, 'Orjen', 'Trebinje', 'orjen-trebinje', '', 1894, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(123, 1, 'Velika Golija', 'Livno', 'velika-golija-livno', '', 1890, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(124, 1, 'Šator', 'Glamoč/Bosansko Grahovo', 'sator-glamoc/bosansko-grahovo', '', 1873, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(125, 1, 'Trebova', 'Foča', 'trebova-foca', '', 1872, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(126, 1, 'Bjelašnica', 'Gacko', 'bjelasnica-gacko', '', 1867, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(127, 1, 'Kamešnica', 'Livno', 'kamesnica-livno', '', 1856, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(128, 1, 'Lovnica', 'Konjic', 'lovnica-konjic', '', 1856, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(129, 1, 'Zec Planina', 'Fojnica', 'zec-planina-fojnica', '', 18475, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(130, 1, 'Malovan', 'Kupres', 'malovan-kupres', '', 1826, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(131, 1, 'Osječanica', 'Glamoč', 'osjecanica-glamoc', '', 1798, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(132, 1, 'Ljubuša', 'Tomislavgrad/Prozor/Kupres', 'ljubusa-tomislavgrad/prozor/kupres', '', 1797, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(133, 1, 'Čabulja', 'Mostar', 'cabulja-mostar', '', 1786, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(134, 1, 'Šćit', 'Kiseljak', 'scit-kiseljak', '', 1781, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(135, 1, 'Plazenica', 'Donji Vakuf/Kupres', 'plazenica-donji-vakuf/kupres', '', 1765, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(136, 1, 'Stožer', 'Bugojno/Kupres', 'stozer-bugojno/kupres', '', 1758, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(137, 1, 'Slovinj', 'Glamoč', 'slovinj-glamoc', '', 1743, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(138, 1, 'Baba', 'Bileća/Gacko', 'baba-bileca/gacko', '', 1735, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(139, 1, 'Lunjevača', 'Drvar', 'lunjevaca-drvar', '', 1707, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(140, 1, 'Rujište', 'Mostar', 'rujiste-mostar', '', 1703, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(141, 1, 'Bitovnja', 'Konjic/Kreševo', 'bitovnja-konjic/kresevo', '', 1700, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(142, 1, 'Kruščica', 'Travnik/Fojnica', 'kruscica-travnik/fojnica', '', 1673, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(143, 1, 'Ujilica', 'Drvar/Bosansko Grahovo', 'ujilica-drvar/bosansko-grahovo', '', 1654, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(144, 1, 'Romanija', 'Pale', 'romanija-pale', '', 1652, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(145, 1, 'Igman', 'Hadžići/Ilidža', 'igman-hadzici/ilidza', '', 1647, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(146, 1, 'Kapić', 'Gacko', 'kapic-gacko', '', 1644, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(147, 1, 'Staretina', 'Livno/Glamoč', 'staretina-livno/glamoc', '', 1633, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(148, 1, 'Trebević', 'Sarajevo', 'trebevic-sarajevo', '', 1629, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(149, 1, 'Osječanica', 'Drvar', 'osjecanica-drvar', '', 1627, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(150, 1, 'Grmeč', 'Bosanski Petrovac/Bosanska Krupa/Bihać', 'grmec-bosanski-petrovac/bosanska-krupa/bihac', '', 1605, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(151, 1, 'Mjedena Glava', 'Gacko', 'mjedena-glava-gacko', '', 1602, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(152, 1, 'Ravašnica', 'Kupres/Bugojno', 'ravasnica-kupres/bugojno', '', 1565, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(153, 1, 'Javor', 'Gacko/Nevesinje', 'javor-gacko/nevesinje', '', 1553, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(154, 1, 'Hrbljina', 'Glamoč', 'hrbljina-glamoc', '', 1543, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(155, 1, 'Vijenac', 'Bosansko Grahovo', 'vijenac-bosansko-grahovo', '', 1539, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(156, 1, 'Žep', 'Han Pijesak', 'zep-han-pijesak', '', 1537, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(157, 1, 'Ivan planina', 'Hadžići/Konjic/Kreševo', 'ivan-planina-hadzici/konjic/kresevo', '', 1534, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(158, 1, 'Ozren', 'Sarajevo', 'ozren-sarajevo', '', 1534, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(159, 1, 'Kovač planina', 'Čajniče', 'kovac-planina-cajnice', '', 1532, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(160, 1, 'Bačina planina', 'Prozor', 'bacina-planina-prozor', '', 1530, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(161, 1, 'Komar', 'Donji Vakuf/Travnik/Bugojno', 'komar-donji-vakuf/travnik/bugojno', '', 1510, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(162, 1, 'Kmur', 'Foča', 'kmur-foca', '', 1508, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(163, 2, 'Dinara', 'Šibensko-kninska', 'dinara-sibensko-kninska', 'Sinjal', 1831, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(164, 2, 'Biokovo', 'Splitsko-dalmatinska', 'biokovo-splitsko-dalmatinska', 'Sveti Jure', 1762, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(165, 2, 'Velebit', 'Ličko-senjska', 'velebit-licko-senjska', 'Vaganski vrh', 1758, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(166, 2, 'Plješivica', 'Zadarska', 'pljesivica-zadarska', 'Kremen', 1591, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(167, 2, 'Bjelolasica', 'Primorsko-goranska', 'bjelolasica-primorsko-goranska', 'Kula', 1533, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(168, 2, 'Velika Kapela', 'Karlovačka', 'velika-kapela-karlovacka', 'Velika Javornica', 1374, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(169, 2, 'Ćićarija', 'Istarska', 'cicarija-istarska', 'Veliki Planik', 1272, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(170, 2, 'Sniježnica', 'Dubrovačko-neretvanska', 'snijeznica-dubrovacko-neretvanska', 'Sveti Ilija', 1234, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(171, 2, 'Ivanščica', 'Krapinsko-zagorska', 'ivanscica-krapinsko-zagorska', 'Ivanščica', 1060, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(172, 2, 'Medvednica', 'Grad Zagreb', 'medvednica-grad-zagreb', 'Sljeme', 1033, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(173, 2, 'Žumberačka gora', 'Zagrebačka', 'zumberacka-gora-zagrebacka', 'bezimeni vrh', 1006, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(174, 2, 'Psunj', 'Požeško-slavonska', 'psunj-pozesko-slavonska', 'Brezovo polje', 985, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(175, 2, 'Papuk', 'Virovitičko-podravska', 'papuk-viroviticko-podravska', 'Papuk', 954, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(176, 2, 'Papuk', 'Bjelovarsko-bilogorska', 'papuk-bjelovarsko-bilogorska', 'Crni vrh', 863, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(177, 2, 'Krndija', 'Osječko-baranjska', 'krndija-osjecko-baranjska', 'Petrov vrh', 701, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(178, 2, 'Ravna gora', 'Varaždinska', 'ravna-gora-varazdinska', 'Ravna gora', 686, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(179, 2, 'Kalnička gora', 'Koprivničko-križevačka', 'kalnicka-gora-koprivnicko-krizevacka', 'Vranilac/Kalnik', 643, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(180, 2, 'Babja gora', 'Brodsko-posavska', 'babja-gora-brodsko-posavska', 'Kapovac', 618, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(181, 2, 'Zrinska gora', 'Sisačko-moslavačka', 'zrinska-gora-sisacko-moslavacka', 'Piramida', 616, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(182, 2, 'Međimurske gorice', 'Međimurska', 'medjimurske-gorice-medjimurska', 'Mohokos', 344, 'Mountain', 0, 0, '');
INSERT INTO `repo_regions` (`id`, `id_parent`, `name`, `region`, `slug`, `desc`, `maxelev`, `type`, `lat_center`, `lon_center`, `bounds`) VALUES(183, 2, 'Fruška gora', 'Vukovarsko-srijemska', 'fruska-gora-vukovarsko-srijemska', 'Liska', 297, 'Mountain', 0, 0, '');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `repo_regions`
--
ALTER TABLE `repo_regions`
  ADD CONSTRAINT `child_parent` FOREIGN KEY (`id_parent`) REFERENCES `repo_regions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
