const Enum = {
    MapEvents: {
        RETRIEVE_MAP_INIT: 'RETRIEVE_MAP_INIT',
        RETRIEVE_INITIAL_DATA_SETUP: 'RETRIEVE_INITIAL_DATA_SETUP',
        INITIAL_MAP_SETUP_RETRIEVED: 'INITIAL_MAP_SETUP_RETRIEVED',
        INITIAL_DATA_SETUP_RETRIEVED: 'INITIAL_DATA_SETUP_RETRIEVED',
    },
    AppEvents: {
        OPEN_FORM_NEW_TRAIL: '__OPEN_FORM_NEW_TRAIL__',
        CHANGE_LANGUAGE: '__CHANGE_LANGUAGE__',
    },
    DataEvents: {
        SAVE_TRAILDATA2MODEL: '_SAVE_TRAILDATA2MODEL_',
        RETRIEVE_TRAIL_DATA: '_RETRIEVE_TRAIL_DATA_',
        TRAIL_DATA_RETRIEVED: '_TRAIL_DATA_RETRIEVED_',
        START_IMAGE_UPLOAD: '_START_IMAGE_UPLOAD_',
        START_GEO_FILE_UPLOAD: '_START_GEO_FILE_UPLOAD_',
    },
    ChartEvents: {
        CHART_POINT_CLICKED: '_CHART_POINT_CLICKED_',
    },
};

export default Enum;
