const Enum = {
    MapEvents: {
        RETRIEVE_MAP_INIT: 'RETRIEVE_MAP_INIT',
        RETRIEVE_INITIAL_DATA_SETUP: 'RETRIEVE_INITIAL_DATA_SETUP',
        INITIAL_MAP_SETUP_RETRIEVED: 'INITIAL_MAP_SETUP_RETRIEVED',
        INITIAL_DATA_SETUP_RETRIEVED: 'INITIAL_DATA_SETUP_RETRIEVED',
    },
};

export default Enum;
