const MessageEvents = {
    ERROR_MESSAGE: '__ERROR_MESSAGE__',
    WARNING_MESSAGE: '__WARNING_MESSAGE__',
    INFO_MESSAGE: '__INFO_MESSAGE__',
    LONGER_INFO_MESSAGE: '__LONGER_INFO_MESSAGE__',
    PROGRESS_MESSAGE: '__PROGRESS_MESSAGE__',
    STATUS_MESSAGE: '__STATUS_MESSAGE__',
    PICTURE_UPLOAD_STATUS: '__PICTURE_UPLOAD_STATUS__',
    GEOFILE_PROCESS_STATUS: '__GEOFILE_PROCESS_STATUS__',
};

export default MessageEvents;
