const MessageEvents = {
    ERROR_MESSAGE: '__ERROR_MESSAGE__',
    WARNING_MESSAGE: '__WARNING_MESSAGE__',
    INFO_MESSAGE: '__ERROR_MESSAGE__',
    PROGRESS_MESSAGE: '__PROGRESS_MESSAGE__',
    STATUS_MESSAGE: '__STATUS_MESSAGE__',
    PICTURE_UPLOAD_STATUS: '__PICTURE_UPLOAD_STATUS__',
    PICTURE_UPLOAD_PROGRESS: '__PICTURE_UPLOAD_PROGRESS__',
    SIMPLIFY_PROGRESS: '__SIMPLIFY_PROGRESS__',
};

export default MessageEvents;
